### ISSUE TITLE
Page title in example code doesn't work

### ISSUE THREAD

**Issue by chrisshroba** [kingdaro/online-pug-compiler#1]
Hi there! In the example Pug file, you have the following:

    title= pageTitle

but I think you meant either 

    title= 'pageTitle'

or 

    title pageTitle

Looks like the offending code is at [main.js:22](https://github.com/kingdaro/online-pug-compiler/blob/master/main.js#L22).

P.S. Thanks so much for making this tool, it's been a great tool for helping me learn pug! :)

**Comment by itsMapleLeaf** [comment]
The code itself _works_, it's just that there's no result because there's no `pageTitle` variable available. It probably would be good to put a literal title there instead of using a variable, but implementing the ability to put variables does sound like an interesting idea.

> P.S. Thanks so much for making this tool, it's been a great tool for helping me learn pug! :)

Sure, glad you like it c:

**Comment by itsMapleLeaf** [comment]
Fixed by https://github.com/kingdaro/online-pug-compiler/commit/63d383e1e736bd9f6ed5fc5c423d605555272a7c
